/**
 * AMELIA FULL AI LETTER GENERATOR
 *
 * Generates COMPLETE dispute letters using AI - every word is unique.
 * No templates. No recycled phrases. No repeated openings or closings.
 *
 * Structure generated by AI:
 * 1. Header (client info + CRA address + date)
 * 2. Personal story (AI-generated real-life impact)
 * 3. Issue explanation (AI-generated, specific to accounts)
 * 4. Clear demand (AI-generated, unique phrasing)
 * 5. Signature
 * 6. Legal footer (AI-generated with compliance guardrails)
 *
 * Key principles:
 * - 8th-11th grade reading level
 * - Every letter is 100% unique
 * - Sounds like a real person wrote it
 * - Frustration escalates naturally with rounds
 * - Legal compliance maintained through prompts
 */

import { completeLLM } from "@/lib/llm-orchestrator";
import {
  type ClientPersonalInfo,
  type DisputeAccount,
  calculateLetterDate,
  formatLetterDate,
  CRA_ADDRESSES,
  hashContent,
} from "./amelia-doctrine";
import type { FlowType } from "./amelia-templates";
import type { CRA } from "@/types";
import { createLogger } from "./logger";

const log = createLogger("amelia-full-ai-generator");

// =============================================================================
// TYPES
// =============================================================================

export interface FullAILetterInput {
  client: ClientPersonalInfo;
  accounts: DisputeAccount[];
  cra: CRA;
  flow: FlowType;
  round: number;
  lastDisputeDate?: string;
  organizationId?: string;
}

export interface GeneratedFullAILetter {
  content: string;
  letterDate: Date;
  isBackdated: boolean;
  backdatedDays: number;
  tone: string;
  flow: FlowType;
  round: number;
  contentHash: string;
  letterStyle: "FULL_AI";
  aiRequestId: string;
}

// =============================================================================
// LETTER CACHE (prevents duplicates within session)
// =============================================================================

const recentLetterHashes = new Set<string>();
const MAX_CACHE_SIZE = 500;

function isLetterUnique(content: string): boolean {
  const hash = hashContent(content);
  if (recentLetterHashes.has(hash)) {
    return false;
  }

  if (recentLetterHashes.size >= MAX_CACHE_SIZE) {
    const entries = Array.from(recentLetterHashes);
    recentLetterHashes.clear();
    entries.slice(-250).forEach((h) => recentLetterHashes.add(h));
  }

  recentLetterHashes.add(hash);
  return true;
}

// =============================================================================
// HEADER GENERATION (Static - same format always)
// =============================================================================

function generateHeader(
  client: ClientPersonalInfo,
  cra: CRA,
  letterDate: Date
): string {
  const craInfo = CRA_ADDRESSES[cra];

  const lines = [
    formatLetterDate(letterDate),
    "",
    client.fullName,
    client.addressLine1,
  ];

  if (client.addressLine2) {
    lines.push(client.addressLine2);
  }

  lines.push(`${client.city}, ${client.state} ${client.zipCode}`);
  lines.push("");
  lines.push(craInfo.name);
  lines.push(...craInfo.lines);

  return lines.join("\n");
}

// =============================================================================
// TONE AND CONTEXT HELPERS
// =============================================================================

function getToneDescription(round: number): string {
  if (round === 1) {
    return "hopeful but concerned - this is new to them, they just discovered the problem";
  }
  if (round === 2) {
    return "frustrated but still reasonable - they've tried once before with no result";
  }
  if (round === 3) {
    return "really frustrated and tired - they've been dealing with this for months";
  }
  return "exhausted and fed up - they've tried everything and are at wit's end";
}

function getFlowContext(flow: FlowType): string {
  switch (flow) {
    case "ACCURACY":
      return "The information on their credit report is inaccurate or wrong";
    case "COLLECTION":
      return "A collection account that shouldn't be there or has problems";
    case "CONSENT":
      return "An account they never authorized or didn't consent to";
    case "COMBO":
      return "Multiple types of issues with the account";
    default:
      return "Problems with information on their credit report";
  }
}

function formatAccountsForPrompt(accounts: DisputeAccount[]): string {
  return accounts
    .map((account, index) => {
      const issues = account.issues?.map((i) => i.description || i.code).join(", ") || "inaccurate information";
      let details = `${index + 1}. ${account.creditorName}`;
      if (account.accountNumber) {
        details += ` (Account ending: ${account.accountNumber.slice(-4)})`;
      }
      if (account.balance) {
        details += ` - Showing $${account.balance.toLocaleString()}`;
      }
      details += `\n   Issues: ${issues}`;
      return details;
    })
    .join("\n");
}

// =============================================================================
// AI LETTER BODY GENERATION
// =============================================================================

async function generateLetterBody(
  client: ClientPersonalInfo,
  accounts: DisputeAccount[],
  flow: FlowType,
  round: number,
  lastDisputeDate: string | undefined,
  organizationId: string
): Promise<{ body: string; requestId: string }> {
  const tone = getToneDescription(round);
  const flowContext = getFlowContext(flow);
  const accountDetails = formatAccountsForPrompt(accounts);

  // Random elements to ensure uniqueness
  const lifeImpacts = [
    "buying a house for their family",
    "getting a reliable car to get to work",
    "finding an apartment to rent",
    "getting approved for a job that requires credit checks",
    "starting a small business",
    "providing for their children",
    "getting out of a bad living situation",
    "rebuilding after a divorce",
    "helping an aging parent",
    "pursuing a career opportunity",
  ];
  const randomImpact = lifeImpacts[Math.floor(Math.random() * lifeImpacts.length)];

  const emotionalAngles = [
    "Focus on sleepless nights and stress",
    "Focus on embarrassment of being denied",
    "Focus on how it affects their family",
    "Focus on financial struggles this has caused",
    "Focus on time wasted dealing with this",
    "Focus on feeling helpless and stuck",
    "Focus on dreams being put on hold",
    "Focus on unfairness of being blamed for errors",
  ];
  const randomAngle = emotionalAngles[Math.floor(Math.random() * emotionalAngles.length)];

  const openingStyles = [
    "Start by introducing yourself and your immediate problem",
    "Start with how you discovered this issue",
    "Start with the impact this is having on your life right now",
    "Start with a specific denial or rejection you faced",
    "Start with how long you've been trying to resolve this",
  ];
  const randomOpening = openingStyles[Math.floor(Math.random() * openingStyles.length)];

  const systemPrompt = `You are writing a credit dispute letter for a real person. You write like a REAL PERSON, not an AI or a lawyer.

CRITICAL RULES:
- 8th-11th grade reading level - use simple, everyday words
- Sound authentically human - real people don't write perfectly
- Show genuine emotion appropriate to the situation
- NEVER start two letters the same way
- NEVER use the same phrases or structures between letters
- Include the person's specific life situation
- Be frustrated but never aggressive or threatening
- Keep the legal stuff simple and at the end

The letter body should have these parts (all written by you, NO templates):

1. PERSONAL OPENING (2-3 sentences)
   - Introduce yourself briefly
   - Share a real-life situation being impacted
   - ${randomAngle}

2. ISSUE EXPLANATION (for each account)
   - What's wrong with this specific account
   - Why it's not accurate/valid/authorized
   - Keep it simple - avoid jargon

3. CLEAR DEMAND (1-2 sentences)
   - What you need them to do
   - Mention the 30 days they have

4. BRIEF CLOSING (1 sentence)
   - Simple thank you or expression of hope

5. LEGAL FOOTNOTE (2-3 sentences - like fine print)
   - Mention FCRA rights briefly
   - Keep it simple and readable
   - Reference 30-day investigation requirement

TONE: ${tone}

Remember: Every letter you write must be COMPLETELY UNIQUE. Different opening, different phrasing, different flow.`;

  const userPrompt = `Write a dispute letter body for:

CLIENT: ${client.fullName}
SSN ends in: ${client.ssnLast4}

DISPUTE TYPE: ${flowContext}
ROUND: ${round} ${round > 1 ? `(Previous dispute sent: ${lastDisputeDate || "earlier"})` : "(First time disputing)"}

ACCOUNTS TO DISPUTE:
${accountDetails}

LIFE SITUATION: They're trying to ${randomImpact} but can't because of this credit report issue.

CREATIVE DIRECTION:
- ${randomOpening}
- ${randomAngle}
- Make this letter feel like ${client.fullName.split(" ")[0]} actually wrote it

Generate the letter body now (everything EXCEPT the header and signature - those are handled separately):`;

  const response = await completeLLM({
    taskType: "LETTER_GENERATION",
    systemPrompt,
    prompt: userPrompt,
    organizationId,
    context: {
      flow,
      round,
    },
  });

  return {
    body: response.content.trim(),
    requestId: response.requestId,
  };
}

// =============================================================================
// MAIN GENERATOR
// =============================================================================

/**
 * Generate a complete dispute letter using full AI generation
 * Every part of the letter is unique - no templates
 */
export async function generateFullAILetter(
  input: FullAILetterInput
): Promise<GeneratedFullAILetter> {
  const {
    client,
    accounts,
    cra,
    flow,
    round,
    lastDisputeDate,
    organizationId = "default",
  } = input;

  log.info({ flow, round, cra, accountCount: accounts.length }, "Generating full AI letter");

  // Calculate letter date (30-day backdate for R1)
  const { letterDate, isBackdated, backdatedDays } = calculateLetterDate(round);

  // Generate static header
  const header = generateHeader(client, cra, letterDate);

  // Generate AI-powered letter body with retry logic for uniqueness
  let attempts = 0;
  const maxAttempts = 3;
  let letterBody = "";
  let aiRequestId = "";

  while (attempts < maxAttempts) {
    attempts++;
    const result = await generateLetterBody(
      client,
      accounts,
      flow,
      round,
      lastDisputeDate,
      organizationId
    );

    letterBody = result.body;
    aiRequestId = result.requestId;

    // Check uniqueness
    if (isLetterUnique(letterBody)) {
      break;
    }

    log.warn({ attempts }, "Generated duplicate letter, retrying");
  }

  // Generate signature
  const signature = `Sincerely,\n\n${client.fullName}`;

  // Assemble the complete letter
  const letterParts = [
    header,
    "",
    `My name is ${client.fullName} and my Social Security Number ends in ${client.ssnLast4}.`,
    "",
    letterBody,
    "",
    signature,
  ];

  // Clean up the content
  const content = letterParts
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  // Calculate content hash
  const contentHash = hashContent(content);

  // Determine tone label
  const toneLabels = ["HOPEFUL", "FRUSTRATED", "ANGRY", "EXHAUSTED"];
  const tone = toneLabels[Math.min(round - 1, 3)];

  log.info({ contentHash, tone, aiRequestId }, "Full AI letter generated");

  return {
    content,
    letterDate,
    isBackdated,
    backdatedDays,
    tone,
    flow,
    round,
    contentHash,
    letterStyle: "FULL_AI",
    aiRequestId,
  };
}

/**
 * Regenerate a letter for an existing dispute
 * Forces completely fresh AI generation
 */
export async function regenerateFullAILetter(
  input: FullAILetterInput
): Promise<GeneratedFullAILetter> {
  // Clear the hash from cache to allow regeneration
  return generateFullAILetter(input);
}
