/**
 * Litigation Workflow Engine — Jurisdiction Data
 *
 * Static reference data for all 50 US states + DC covering federal district
 * courts, small claims limits, state attorney general offices, and civil
 * service-of-process requirements.
 *
 * All monetary values are expressed in **cents** (USD * 100).
 */

import type {
  FederalDistrict,
  SmallClaimsInfo,
  StateAGInfo,
  ServiceRequirements,
} from "./types";

// ============================================================================
// Federal District Courts
// ============================================================================

/** Federal district courts for every US state and DC, keyed by two-letter state code. */
export const FEDERAL_DISTRICTS = {
  AL: [
    {
      name: "United States District Court for the Northern District of Alabama",
      shortName: "N.D. Ala.",
      courtAddress: "1729 5th Avenue North, Birmingham, AL 35203",
      filingFee: 40500,
      divisions: ["Birmingham", "Decatur", "Florence", "Gadsden", "Huntsville", "Jasper", "Tuscaloosa"],
    },
    {
      name: "United States District Court for the Middle District of Alabama",
      shortName: "M.D. Ala.",
      courtAddress: "One Church Street, Montgomery, AL 36104",
      filingFee: 40500,
      divisions: ["Montgomery", "Dothan", "Opelika"],
    },
    {
      name: "United States District Court for the Southern District of Alabama",
      shortName: "S.D. Ala.",
      courtAddress: "155 St. Joseph Street, Mobile, AL 36602",
      filingFee: 40500,
      divisions: ["Mobile", "Selma"],
    },
  ],
  AK: [
    {
      name: "United States District Court for the District of Alaska",
      shortName: "D. Alaska",
      courtAddress: "222 West 7th Avenue, Anchorage, AK 99513",
      filingFee: 40500,
    },
  ],
  AZ: [
    {
      name: "United States District Court for the District of Arizona",
      shortName: "D. Ariz.",
      courtAddress: "401 West Washington Street, Phoenix, AZ 85003",
      filingFee: 40500,
      divisions: ["Phoenix", "Tucson", "Prescott", "Flagstaff"],
    },
  ],
  AR: [
    {
      name: "United States District Court for the Eastern District of Arkansas",
      shortName: "E.D. Ark.",
      courtAddress: "600 West Capitol Avenue, Little Rock, AR 72201",
      filingFee: 40500,
      divisions: ["Little Rock", "Helena", "Jonesboro", "Pine Bluff", "Batesville"],
    },
    {
      name: "United States District Court for the Western District of Arkansas",
      shortName: "W.D. Ark.",
      courtAddress: "35 East Mountain Street, Fayetteville, AR 72701",
      filingFee: 40500,
      divisions: ["Fayetteville", "Fort Smith", "Harrison", "Hot Springs", "Texarkana", "El Dorado"],
    },
  ],
  CA: [
    {
      name: "United States District Court for the Northern District of California",
      shortName: "N.D. Cal.",
      courtAddress: "450 Golden Gate Avenue, San Francisco, CA 94102",
      filingFee: 40500,
      divisions: ["San Francisco", "Oakland", "San Jose", "Eureka"],
    },
    {
      name: "United States District Court for the Central District of California",
      shortName: "C.D. Cal.",
      courtAddress: "350 West 1st Street, Los Angeles, CA 90012",
      filingFee: 40500,
      divisions: ["Los Angeles", "Santa Ana", "Riverside"],
    },
    {
      name: "United States District Court for the Eastern District of California",
      shortName: "E.D. Cal.",
      courtAddress: "501 I Street, Sacramento, CA 95814",
      filingFee: 40500,
      divisions: ["Sacramento", "Fresno"],
    },
    {
      name: "United States District Court for the Southern District of California",
      shortName: "S.D. Cal.",
      courtAddress: "333 West Broadway, San Diego, CA 92101",
      filingFee: 40500,
    },
  ],
  CO: [
    {
      name: "United States District Court for the District of Colorado",
      shortName: "D. Colo.",
      courtAddress: "901 19th Street, Denver, CO 80294",
      filingFee: 40500,
    },
  ],
  CT: [
    {
      name: "United States District Court for the District of Connecticut",
      shortName: "D. Conn.",
      courtAddress: "141 Church Street, New Haven, CT 06510",
      filingFee: 40500,
      divisions: ["New Haven", "Hartford", "Bridgeport"],
    },
  ],
  DE: [
    {
      name: "United States District Court for the District of Delaware",
      shortName: "D. Del.",
      courtAddress: "844 North King Street, Wilmington, DE 19801",
      filingFee: 40500,
    },
  ],
  DC: [
    {
      name: "United States District Court for the District of Columbia",
      shortName: "D.D.C.",
      courtAddress: "333 Constitution Avenue NW, Washington, DC 20001",
      filingFee: 40500,
    },
  ],
  FL: [
    {
      name: "United States District Court for the Southern District of Florida",
      shortName: "S.D. Fla.",
      courtAddress: "400 North Miami Avenue, Miami, FL 33128",
      filingFee: 40500,
      divisions: ["Miami", "Fort Lauderdale", "West Palm Beach", "Fort Pierce", "Key West"],
    },
    {
      name: "United States District Court for the Middle District of Florida",
      shortName: "M.D. Fla.",
      courtAddress: "300 North Hogan Street, Jacksonville, FL 32202",
      filingFee: 40500,
      divisions: ["Jacksonville", "Orlando", "Tampa", "Fort Myers", "Ocala"],
    },
    {
      name: "United States District Court for the Northern District of Florida",
      shortName: "N.D. Fla.",
      courtAddress: "111 North Adams Street, Tallahassee, FL 32301",
      filingFee: 40500,
      divisions: ["Tallahassee", "Pensacola", "Panama City", "Gainesville"],
    },
  ],
  GA: [
    {
      name: "United States District Court for the Northern District of Georgia",
      shortName: "N.D. Ga.",
      courtAddress: "75 Ted Turner Drive SW, Atlanta, GA 30303",
      filingFee: 40500,
      divisions: ["Atlanta", "Gainesville", "Newnan", "Rome"],
    },
    {
      name: "United States District Court for the Middle District of Georgia",
      shortName: "M.D. Ga.",
      courtAddress: "475 Mulberry Street, Macon, GA 31201",
      filingFee: 40500,
      divisions: ["Macon", "Albany", "Athens", "Columbus", "Valdosta"],
    },
    {
      name: "United States District Court for the Southern District of Georgia",
      shortName: "S.D. Ga.",
      courtAddress: "125 Bull Street, Savannah, GA 31401",
      filingFee: 40500,
      divisions: ["Savannah", "Augusta", "Brunswick", "Dublin", "Statesboro", "Waycross"],
    },
  ],
  HI: [
    {
      name: "United States District Court for the District of Hawaii",
      shortName: "D. Haw.",
      courtAddress: "300 Ala Moana Boulevard, Honolulu, HI 96850",
      filingFee: 40500,
    },
  ],
  ID: [
    {
      name: "United States District Court for the District of Idaho",
      shortName: "D. Idaho",
      courtAddress: "550 West Fort Street, Boise, ID 83724",
      filingFee: 40500,
      divisions: ["Boise", "Coeur d'Alene", "Moscow", "Pocatello"],
    },
  ],
  IL: [
    {
      name: "United States District Court for the Northern District of Illinois",
      shortName: "N.D. Ill.",
      courtAddress: "219 South Dearborn Street, Chicago, IL 60604",
      filingFee: 40500,
      divisions: ["Chicago", "Rockford"],
    },
    {
      name: "United States District Court for the Central District of Illinois",
      shortName: "C.D. Ill.",
      courtAddress: "600 East Monroe Street, Springfield, IL 62701",
      filingFee: 40500,
      divisions: ["Springfield", "Peoria", "Urbana", "Rock Island"],
    },
    {
      name: "United States District Court for the Southern District of Illinois",
      shortName: "S.D. Ill.",
      courtAddress: "750 Missouri Avenue, East St. Louis, IL 62201",
      filingFee: 40500,
      divisions: ["East St. Louis", "Benton"],
    },
  ],
  IN: [
    {
      name: "United States District Court for the Northern District of Indiana",
      shortName: "N.D. Ind.",
      courtAddress: "204 South Main Street, South Bend, IN 46601",
      filingFee: 40500,
      divisions: ["South Bend", "Fort Wayne", "Hammond", "Lafayette"],
    },
    {
      name: "United States District Court for the Southern District of Indiana",
      shortName: "S.D. Ind.",
      courtAddress: "46 East Ohio Street, Indianapolis, IN 46204",
      filingFee: 40500,
      divisions: ["Indianapolis", "Evansville", "New Albany", "Terre Haute"],
    },
  ],
  IA: [
    {
      name: "United States District Court for the Northern District of Iowa",
      shortName: "N.D. Iowa",
      courtAddress: "111 7th Avenue SE, Cedar Rapids, IA 52401",
      filingFee: 40500,
      divisions: ["Cedar Rapids", "Sioux City", "Fort Dodge", "Dubuque", "Waterloo"],
    },
    {
      name: "United States District Court for the Southern District of Iowa",
      shortName: "S.D. Iowa",
      courtAddress: "123 East Walnut Street, Des Moines, IA 50309",
      filingFee: 40500,
      divisions: ["Des Moines", "Council Bluffs", "Davenport", "Ottumwa"],
    },
  ],
  KS: [
    {
      name: "United States District Court for the District of Kansas",
      shortName: "D. Kan.",
      courtAddress: "500 State Avenue, Kansas City, KS 66101",
      filingFee: 40500,
      divisions: ["Kansas City", "Topeka", "Wichita"],
    },
  ],
  KY: [
    {
      name: "United States District Court for the Eastern District of Kentucky",
      shortName: "E.D. Ky.",
      courtAddress: "35 West 5th Street, Covington, KY 41011",
      filingFee: 40500,
      divisions: ["Lexington", "Covington", "Ashland", "Frankfort", "London", "Pikeville"],
    },
    {
      name: "United States District Court for the Western District of Kentucky",
      shortName: "W.D. Ky.",
      courtAddress: "601 West Broadway, Louisville, KY 40202",
      filingFee: 40500,
      divisions: ["Louisville", "Bowling Green", "Owensboro", "Paducah"],
    },
  ],
  LA: [
    {
      name: "United States District Court for the Eastern District of Louisiana",
      shortName: "E.D. La.",
      courtAddress: "500 Poydras Street, New Orleans, LA 70130",
      filingFee: 40500,
    },
    {
      name: "United States District Court for the Middle District of Louisiana",
      shortName: "M.D. La.",
      courtAddress: "777 Florida Street, Baton Rouge, LA 70801",
      filingFee: 40500,
    },
    {
      name: "United States District Court for the Western District of Louisiana",
      shortName: "W.D. La.",
      courtAddress: "300 Fannin Street, Shreveport, LA 71101",
      filingFee: 40500,
      divisions: ["Shreveport", "Alexandria", "Lafayette", "Lake Charles", "Monroe"],
    },
  ],
  ME: [
    {
      name: "United States District Court for the District of Maine",
      shortName: "D. Me.",
      courtAddress: "156 Federal Street, Portland, ME 04101",
      filingFee: 40500,
      divisions: ["Portland", "Bangor"],
    },
  ],
  MD: [
    {
      name: "United States District Court for the District of Maryland",
      shortName: "D. Md.",
      courtAddress: "101 West Lombard Street, Baltimore, MD 21201",
      filingFee: 40500,
      divisions: ["Baltimore", "Greenbelt"],
    },
  ],
  MA: [
    {
      name: "United States District Court for the District of Massachusetts",
      shortName: "D. Mass.",
      courtAddress: "1 Courthouse Way, Boston, MA 02210",
      filingFee: 40500,
      divisions: ["Boston", "Springfield", "Worcester"],
    },
  ],
  MI: [
    {
      name: "United States District Court for the Eastern District of Michigan",
      shortName: "E.D. Mich.",
      courtAddress: "231 West Lafayette Boulevard, Detroit, MI 48226",
      filingFee: 40500,
      divisions: ["Detroit", "Ann Arbor", "Bay City", "Flint", "Port Huron"],
    },
    {
      name: "United States District Court for the Western District of Michigan",
      shortName: "W.D. Mich.",
      courtAddress: "110 Michigan Street NW, Grand Rapids, MI 49503",
      filingFee: 40500,
      divisions: ["Grand Rapids", "Kalamazoo", "Lansing", "Marquette"],
    },
  ],
  MN: [
    {
      name: "United States District Court for the District of Minnesota",
      shortName: "D. Minn.",
      courtAddress: "300 South Fourth Street, Minneapolis, MN 55415",
      filingFee: 40500,
      divisions: ["Minneapolis", "St. Paul", "Duluth", "Fergus Falls"],
    },
  ],
  MS: [
    {
      name: "United States District Court for the Northern District of Mississippi",
      shortName: "N.D. Miss.",
      courtAddress: "911 Jackson Avenue, Oxford, MS 38655",
      filingFee: 40500,
      divisions: ["Oxford", "Aberdeen", "Greenville"],
    },
    {
      name: "United States District Court for the Southern District of Mississippi",
      shortName: "S.D. Miss.",
      courtAddress: "501 East Court Street, Jackson, MS 39201",
      filingFee: 40500,
      divisions: ["Jackson", "Hattiesburg", "Gulfport", "Natchez"],
    },
  ],
  MO: [
    {
      name: "United States District Court for the Eastern District of Missouri",
      shortName: "E.D. Mo.",
      courtAddress: "111 South 10th Street, St. Louis, MO 63102",
      filingFee: 40500,
      divisions: ["St. Louis", "Cape Girardeau", "Hannibal"],
    },
    {
      name: "United States District Court for the Western District of Missouri",
      shortName: "W.D. Mo.",
      courtAddress: "400 East 9th Street, Kansas City, MO 64106",
      filingFee: 40500,
      divisions: ["Kansas City", "Jefferson City", "Joplin", "Springfield", "St. Joseph"],
    },
  ],
  MT: [
    {
      name: "United States District Court for the District of Montana",
      shortName: "D. Mont.",
      courtAddress: "316 North 26th Street, Billings, MT 59101",
      filingFee: 40500,
      divisions: ["Billings", "Butte", "Great Falls", "Helena", "Missoula"],
    },
  ],
  NE: [
    {
      name: "United States District Court for the District of Nebraska",
      shortName: "D. Neb.",
      courtAddress: "111 South 18th Plaza, Omaha, NE 68102",
      filingFee: 40500,
      divisions: ["Omaha", "Lincoln", "North Platte"],
    },
  ],
  NV: [
    {
      name: "United States District Court for the District of Nevada",
      shortName: "D. Nev.",
      courtAddress: "333 Las Vegas Boulevard South, Las Vegas, NV 89101",
      filingFee: 40500,
      divisions: ["Las Vegas", "Reno"],
    },
  ],
  NH: [
    {
      name: "United States District Court for the District of New Hampshire",
      shortName: "D.N.H.",
      courtAddress: "55 Pleasant Street, Concord, NH 03301",
      filingFee: 40500,
    },
  ],
  NJ: [
    {
      name: "United States District Court for the District of New Jersey",
      shortName: "D.N.J.",
      courtAddress: "402 East State Street, Trenton, NJ 08608",
      filingFee: 40500,
      divisions: ["Trenton", "Newark", "Camden"],
    },
  ],
  NM: [
    {
      name: "United States District Court for the District of New Mexico",
      shortName: "D.N.M.",
      courtAddress: "333 Lomas Boulevard NW, Albuquerque, NM 87102",
      filingFee: 40500,
      divisions: ["Albuquerque", "Las Cruces"],
    },
  ],
  NY: [
    {
      name: "United States District Court for the Southern District of New York",
      shortName: "S.D.N.Y.",
      courtAddress: "500 Pearl Street, New York, NY 10007",
      filingFee: 40500,
      divisions: ["Manhattan", "White Plains"],
    },
    {
      name: "United States District Court for the Eastern District of New York",
      shortName: "E.D.N.Y.",
      courtAddress: "225 Cadman Plaza East, Brooklyn, NY 11201",
      filingFee: 40500,
      divisions: ["Brooklyn", "Central Islip"],
    },
    {
      name: "United States District Court for the Northern District of New York",
      shortName: "N.D.N.Y.",
      courtAddress: "445 Broadway, Albany, NY 12207",
      filingFee: 40500,
      divisions: ["Albany", "Syracuse", "Binghamton", "Utica", "Plattsburgh"],
    },
    {
      name: "United States District Court for the Western District of New York",
      shortName: "W.D.N.Y.",
      courtAddress: "2 Niagara Square, Buffalo, NY 14202",
      filingFee: 40500,
      divisions: ["Buffalo", "Rochester"],
    },
  ],
  NC: [
    {
      name: "United States District Court for the Eastern District of North Carolina",
      shortName: "E.D.N.C.",
      courtAddress: "310 New Bern Avenue, Raleigh, NC 27601",
      filingFee: 40500,
      divisions: ["Raleigh", "Greenville", "Elizabeth City", "Wilmington"],
    },
    {
      name: "United States District Court for the Middle District of North Carolina",
      shortName: "M.D.N.C.",
      courtAddress: "324 West Market Street, Greensboro, NC 27401",
      filingFee: 40500,
      divisions: ["Greensboro", "Durham", "Winston-Salem"],
    },
    {
      name: "United States District Court for the Western District of North Carolina",
      shortName: "W.D.N.C.",
      courtAddress: "401 West Trade Street, Charlotte, NC 28202",
      filingFee: 40500,
      divisions: ["Charlotte", "Asheville", "Statesville", "Bryson City"],
    },
  ],
  ND: [
    {
      name: "United States District Court for the District of North Dakota",
      shortName: "D.N.D.",
      courtAddress: "655 1st Avenue North, Fargo, ND 58102",
      filingFee: 40500,
      divisions: ["Fargo", "Bismarck", "Grand Forks", "Minot"],
    },
  ],
  OH: [
    {
      name: "United States District Court for the Northern District of Ohio",
      shortName: "N.D. Ohio",
      courtAddress: "801 West Superior Avenue, Cleveland, OH 44113",
      filingFee: 40500,
      divisions: ["Cleveland", "Akron", "Toledo", "Youngstown"],
    },
    {
      name: "United States District Court for the Southern District of Ohio",
      shortName: "S.D. Ohio",
      courtAddress: "85 Marconi Boulevard, Columbus, OH 43215",
      filingFee: 40500,
      divisions: ["Columbus", "Cincinnati", "Dayton"],
    },
  ],
  OK: [
    {
      name: "United States District Court for the Northern District of Oklahoma",
      shortName: "N.D. Okla.",
      courtAddress: "333 West 4th Street, Tulsa, OK 74103",
      filingFee: 40500,
    },
    {
      name: "United States District Court for the Eastern District of Oklahoma",
      shortName: "E.D. Okla.",
      courtAddress: "101 North 5th Street, Muskogee, OK 74401",
      filingFee: 40500,
    },
    {
      name: "United States District Court for the Western District of Oklahoma",
      shortName: "W.D. Okla.",
      courtAddress: "200 NW 4th Street, Oklahoma City, OK 73102",
      filingFee: 40500,
    },
  ],
  OR: [
    {
      name: "United States District Court for the District of Oregon",
      shortName: "D. Or.",
      courtAddress: "1000 SW Third Avenue, Portland, OR 97204",
      filingFee: 40500,
      divisions: ["Portland", "Eugene", "Medford", "Pendleton"],
    },
  ],
  PA: [
    {
      name: "United States District Court for the Eastern District of Pennsylvania",
      shortName: "E.D. Pa.",
      courtAddress: "601 Market Street, Philadelphia, PA 19106",
      filingFee: 40500,
      divisions: ["Philadelphia", "Allentown", "Reading"],
    },
    {
      name: "United States District Court for the Middle District of Pennsylvania",
      shortName: "M.D. Pa.",
      courtAddress: "228 Walnut Street, Harrisburg, PA 17108",
      filingFee: 40500,
      divisions: ["Harrisburg", "Scranton", "Williamsport"],
    },
    {
      name: "United States District Court for the Western District of Pennsylvania",
      shortName: "W.D. Pa.",
      courtAddress: "700 Grant Street, Pittsburgh, PA 15219",
      filingFee: 40500,
      divisions: ["Pittsburgh", "Erie", "Johnstown"],
    },
  ],
  RI: [
    {
      name: "United States District Court for the District of Rhode Island",
      shortName: "D.R.I.",
      courtAddress: "One Exchange Terrace, Providence, RI 02903",
      filingFee: 40500,
    },
  ],
  SC: [
    {
      name: "United States District Court for the District of South Carolina",
      shortName: "D.S.C.",
      courtAddress: "901 Richland Street, Columbia, SC 29201",
      filingFee: 40500,
      divisions: ["Columbia", "Charleston", "Greenville", "Florence", "Aiken", "Beaufort", "Rock Hill", "Spartanburg", "Anderson", "Orangeburg"],
    },
  ],
  SD: [
    {
      name: "United States District Court for the District of South Dakota",
      shortName: "D.S.D.",
      courtAddress: "400 South Phillips Avenue, Sioux Falls, SD 57104",
      filingFee: 40500,
      divisions: ["Sioux Falls", "Pierre", "Rapid City", "Aberdeen"],
    },
  ],
  TN: [
    {
      name: "United States District Court for the Eastern District of Tennessee",
      shortName: "E.D. Tenn.",
      courtAddress: "800 Market Street, Knoxville, TN 37902",
      filingFee: 40500,
      divisions: ["Knoxville", "Chattanooga", "Greeneville", "Winchester"],
    },
    {
      name: "United States District Court for the Middle District of Tennessee",
      shortName: "M.D. Tenn.",
      courtAddress: "719 Church Street, Nashville, TN 37203",
      filingFee: 40500,
      divisions: ["Nashville", "Columbia", "Cookeville"],
    },
    {
      name: "United States District Court for the Western District of Tennessee",
      shortName: "W.D. Tenn.",
      courtAddress: "167 North Main Street, Memphis, TN 38103",
      filingFee: 40500,
      divisions: ["Memphis", "Jackson"],
    },
  ],
  TX: [
    {
      name: "United States District Court for the Northern District of Texas",
      shortName: "N.D. Tex.",
      courtAddress: "1100 Commerce Street, Dallas, TX 75242",
      filingFee: 40500,
      divisions: ["Dallas", "Fort Worth", "Abilene", "Amarillo", "Lubbock", "San Angelo", "Wichita Falls"],
    },
    {
      name: "United States District Court for the Southern District of Texas",
      shortName: "S.D. Tex.",
      courtAddress: "515 Rusk Avenue, Houston, TX 77002",
      filingFee: 40500,
      divisions: ["Houston", "Galveston", "Brownsville", "Corpus Christi", "Laredo", "McAllen", "Victoria"],
    },
    {
      name: "United States District Court for the Eastern District of Texas",
      shortName: "E.D. Tex.",
      courtAddress: "211 West Ferguson Street, Tyler, TX 75702",
      filingFee: 40500,
      divisions: ["Tyler", "Beaumont", "Lufkin", "Marshall", "Sherman", "Texarkana"],
    },
    {
      name: "United States District Court for the Western District of Texas",
      shortName: "W.D. Tex.",
      courtAddress: "655 East Cesar Chavez Boulevard, San Antonio, TX 78206",
      filingFee: 40500,
      divisions: ["San Antonio", "Austin", "Del Rio", "El Paso", "Midland-Odessa", "Pecos", "Waco"],
    },
  ],
  UT: [
    {
      name: "United States District Court for the District of Utah",
      shortName: "D. Utah",
      courtAddress: "351 South West Temple, Salt Lake City, UT 84101",
      filingFee: 40500,
      divisions: ["Salt Lake City", "St. George"],
    },
  ],
  VT: [
    {
      name: "United States District Court for the District of Vermont",
      shortName: "D. Vt.",
      courtAddress: "11 Elmwood Avenue, Burlington, VT 05401",
      filingFee: 40500,
    },
  ],
  VA: [
    {
      name: "United States District Court for the Eastern District of Virginia",
      shortName: "E.D. Va.",
      courtAddress: "401 Courthouse Square, Alexandria, VA 22314",
      filingFee: 40500,
      divisions: ["Alexandria", "Norfolk", "Newport News", "Richmond"],
    },
    {
      name: "United States District Court for the Western District of Virginia",
      shortName: "W.D. Va.",
      courtAddress: "255 West Main Street, Charlottesville, VA 22902",
      filingFee: 40500,
      divisions: ["Charlottesville", "Roanoke", "Lynchburg", "Harrisonburg", "Danville", "Big Stone Gap", "Abingdon"],
    },
  ],
  WA: [
    {
      name: "United States District Court for the Western District of Washington",
      shortName: "W.D. Wash.",
      courtAddress: "700 Stewart Street, Seattle, WA 98101",
      filingFee: 40500,
      divisions: ["Seattle", "Tacoma"],
    },
    {
      name: "United States District Court for the Eastern District of Washington",
      shortName: "E.D. Wash.",
      courtAddress: "920 West Riverside Avenue, Spokane, WA 99201",
      filingFee: 40500,
      divisions: ["Spokane", "Yakima", "Richland"],
    },
  ],
  WV: [
    {
      name: "United States District Court for the Northern District of West Virginia",
      shortName: "N.D. W. Va.",
      courtAddress: "1125 Chapline Street, Wheeling, WV 26003",
      filingFee: 40500,
      divisions: ["Wheeling", "Clarksburg", "Elkins", "Martinsburg"],
    },
    {
      name: "United States District Court for the Southern District of West Virginia",
      shortName: "S.D. W. Va.",
      courtAddress: "300 Virginia Street East, Charleston, WV 25301",
      filingFee: 40500,
      divisions: ["Charleston", "Huntington", "Beckley", "Bluefield", "Parkersburg"],
    },
  ],
  WI: [
    {
      name: "United States District Court for the Eastern District of Wisconsin",
      shortName: "E.D. Wis.",
      courtAddress: "517 East Wisconsin Avenue, Milwaukee, WI 53202",
      filingFee: 40500,
      divisions: ["Milwaukee", "Green Bay"],
    },
    {
      name: "United States District Court for the Western District of Wisconsin",
      shortName: "W.D. Wis.",
      courtAddress: "120 North Henry Street, Madison, WI 53703",
      filingFee: 40500,
    },
  ],
  WY: [
    {
      name: "United States District Court for the District of Wyoming",
      shortName: "D. Wyo.",
      courtAddress: "2120 Capitol Avenue, Cheyenne, WY 82001",
      filingFee: 40500,
    },
  ],
} as const satisfies Record<string, FederalDistrict[]>;

// ============================================================================
// Small Claims Court Limits
// ============================================================================

/** Small claims court monetary limits and filing fee ranges by state (all values in cents). */
export const SMALL_CLAIMS_LIMITS = {
  AL: {
    limit: 600000,
    filingFeeMin: 5000,
    filingFeeMax: 10000,
    notes: "Filed in Small Claims Court (District Court).",
  },
  AK: {
    limit: 1000000,
    filingFeeMin: 3000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Court (District Court).",
  },
  AZ: {
    limit: 350000,
    filingFeeMin: 3500,
    filingFeeMax: 7500,
    notes: "Filed in Justice Court.",
  },
  AR: {
    limit: 500000,
    filingFeeMin: 3000,
    filingFeeMax: 6500,
    notes: "Filed in Small Claims Division of District Court.",
  },
  CA: {
    limit: 1250000,
    filingFeeMin: 3000,
    filingFeeMax: 7500,
    notes: "Individuals may file up to $12,500. Businesses limited to $5,000.",
  },
  CO: {
    limit: 750000,
    filingFeeMin: 3100,
    filingFeeMax: 5500,
    notes: "Filed in County Court, Small Claims Division.",
  },
  CT: {
    limit: 500000,
    filingFeeMin: 3500,
    filingFeeMax: 9500,
    notes: "Filed in Small Claims session of Superior Court.",
  },
  DE: {
    limit: 2500000,
    filingFeeMin: 3500,
    filingFeeMax: 5000,
    notes: "Filed in Justice of the Peace Court.",
  },
  DC: {
    limit: 1000000,
    filingFeeMin: 5000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims and Conciliation Branch of Superior Court.",
  },
  FL: {
    limit: 800000,
    filingFeeMin: 5500,
    filingFeeMax: 30000,
    notes: "Filed in County Court, Small Claims Division. Filing fee varies by county.",
  },
  GA: {
    limit: 1500000,
    filingFeeMin: 4500,
    filingFeeMax: 7500,
    notes: "Filed in Magistrate Court.",
  },
  HI: {
    limit: 500000,
    filingFeeMin: 3500,
    filingFeeMax: 6300,
    notes: "Filed in Small Claims Division of District Court.",
  },
  ID: {
    limit: 500000,
    filingFeeMin: 6900,
    filingFeeMax: 6900,
    notes: "Filed in Magistrate Division of District Court.",
  },
  IL: {
    limit: 1000000,
    filingFeeMin: 4000,
    filingFeeMax: 10000,
    notes: "Filed in Small Claims Court (Circuit Court). Fees vary by county.",
  },
  IN: {
    limit: 1000000,
    filingFeeMin: 3500,
    filingFeeMax: 9700,
    notes: "Filed in Small Claims Court. Township/Marion County has different rules.",
  },
  IA: {
    limit: 650000,
    filingFeeMin: 3500,
    filingFeeMax: 6000,
    notes: "Filed in Small Claims Division of District Court.",
  },
  KS: {
    limit: 400000,
    filingFeeMin: 4500,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Division of District Court.",
  },
  KY: {
    limit: 250000,
    filingFeeMin: 2000,
    filingFeeMax: 5000,
    notes: "Filed in Small Claims Division of District Court.",
  },
  LA: {
    limit: 500000,
    filingFeeMin: 3500,
    filingFeeMax: 10000,
    notes: "Filed in Small Claims Division of City Court or Justice of the Peace Court.",
  },
  ME: {
    limit: 600000,
    filingFeeMin: 5000,
    filingFeeMax: 8000,
    notes: "Filed in Small Claims Court (District Court).",
  },
  MD: {
    limit: 500000,
    filingFeeMin: 3400,
    filingFeeMax: 5000,
    notes: "Filed in District Court, Small Claims Division.",
  },
  MA: {
    limit: 700000,
    filingFeeMin: 4000,
    filingFeeMax: 6500,
    notes: "Filed in Small Claims session of the District Court or Boston Municipal Court.",
  },
  MI: {
    limit: 650000,
    filingFeeMin: 3000,
    filingFeeMax: 7000,
    notes: "Filed in Small Claims Division of District Court.",
  },
  MN: {
    limit: 1500000,
    filingFeeMin: 5500,
    filingFeeMax: 8000,
    notes: "Filed in Conciliation Court (District Court).",
  },
  MS: {
    limit: 350000,
    filingFeeMin: 3500,
    filingFeeMax: 6000,
    notes: "Filed in Justice Court.",
  },
  MO: {
    limit: 500000,
    filingFeeMin: 3000,
    filingFeeMax: 5000,
    notes: "Filed in Small Claims Division of Circuit Court.",
  },
  MT: {
    limit: 700000,
    filingFeeMin: 3000,
    filingFeeMax: 5000,
    notes: "Filed in Small Claims Court (Justice Court or City Court).",
  },
  NE: {
    limit: 360000,
    filingFeeMin: 2600,
    filingFeeMax: 5000,
    notes: "Filed in Small Claims Court (County Court).",
  },
  NV: {
    limit: 1000000,
    filingFeeMin: 3600,
    filingFeeMax: 8000,
    notes: "Filed in Small Claims Division of Justice Court.",
  },
  NH: {
    limit: 1000000,
    filingFeeMin: 4000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Division of District Court.",
  },
  NJ: {
    limit: 500000,
    filingFeeMin: 3000,
    filingFeeMax: 5400,
    notes: "Filed in Small Claims Division of Special Civil Part, Superior Court.",
  },
  NM: {
    limit: 1000000,
    filingFeeMin: 4200,
    filingFeeMax: 7500,
    notes: "Filed in Metropolitan Court or Magistrate Court.",
  },
  NY: {
    limit: 1000000,
    filingFeeMin: 3000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Part of City Court, District Court, or Justice Court.",
  },
  NC: {
    limit: 1000000,
    filingFeeMin: 3600,
    filingFeeMax: 9600,
    notes: "Filed in Small Claims Division of District Court (Magistrate).",
  },
  ND: {
    limit: 1500000,
    filingFeeMin: 3000,
    filingFeeMax: 7000,
    notes: "Filed in Small Claims Division of District Court.",
  },
  OH: {
    limit: 600000,
    filingFeeMin: 4000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Division of Municipal or County Court.",
  },
  OK: {
    limit: 1000000,
    filingFeeMin: 4000,
    filingFeeMax: 8500,
    notes: "Filed in Small Claims Division of District Court.",
  },
  OR: {
    limit: 1000000,
    filingFeeMin: 3500,
    filingFeeMax: 7700,
    notes: "Filed in Small Claims Department of Circuit Court or Justice Court.",
  },
  PA: {
    limit: 1200000,
    filingFeeMin: 5000,
    filingFeeMax: 10000,
    notes: "Filed in Magisterial District Judge Court.",
  },
  RI: {
    limit: 250000,
    filingFeeMin: 3000,
    filingFeeMax: 6500,
    notes: "Filed in Small Claims Division of District Court.",
  },
  SC: {
    limit: 750000,
    filingFeeMin: 4000,
    filingFeeMax: 8000,
    notes: "Filed in Magistrate Court.",
  },
  SD: {
    limit: 1200000,
    filingFeeMin: 4000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Court (Circuit Court).",
  },
  TN: {
    limit: 2500000,
    filingFeeMin: 4400,
    filingFeeMax: 10000,
    notes: "Filed in General Sessions Court.",
  },
  TX: {
    limit: 2000000,
    filingFeeMin: 3500,
    filingFeeMax: 10000,
    notes: "Filed in Small Claims Court (Justice Court). Claim limit recently increased.",
  },
  UT: {
    limit: 1100000,
    filingFeeMin: 6000,
    filingFeeMax: 9500,
    notes: "Filed in Small Claims Department of Justice Court.",
  },
  VT: {
    limit: 500000,
    filingFeeMin: 7500,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Division of Superior Court.",
  },
  VA: {
    limit: 500000,
    filingFeeMin: 4600,
    filingFeeMax: 6200,
    notes: "Filed in Small Claims Division of General District Court.",
  },
  WA: {
    limit: 1000000,
    filingFeeMin: 3000,
    filingFeeMax: 7500,
    notes: "Filed in Small Claims Department of District Court.",
  },
  WV: {
    limit: 1000000,
    filingFeeMin: 3000,
    filingFeeMax: 7500,
    notes: "Filed in Magistrate Court.",
  },
  WI: {
    limit: 1000000,
    filingFeeMin: 4500,
    filingFeeMax: 9500,
    notes: "Filed in Small Claims Division of Circuit Court.",
  },
  WY: {
    limit: 600000,
    filingFeeMin: 3000,
    filingFeeMax: 5000,
    notes: "Filed in Small Claims Court (Circuit Court).",
  },
} as const satisfies Record<string, SmallClaimsInfo>;

// ============================================================================
// State Attorney General Consumer Protection Offices
// ============================================================================

/** State Attorney General consumer protection / consumer complaint addresses for all 50 states + DC. */
export const STATE_AG_ADDRESSES = {
  AL: {
    name: "Alabama Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "501 Washington Avenue",
    city: "Montgomery",
    state: "AL",
    zipCode: "36130",
    phone: "(334) 242-7334",
    url: "https://www.alabamaag.gov/consumer-protection/",
  },
  AK: {
    name: "Alaska Attorney General",
    divisionName: "Consumer Protection Unit",
    addressLine1: "1031 West 4th Avenue, Suite 200",
    city: "Anchorage",
    state: "AK",
    zipCode: "99501",
    phone: "(907) 269-5200",
    url: "https://law.alaska.gov/department/civil/consumer_protection.html",
  },
  AZ: {
    name: "Arizona Attorney General",
    divisionName: "Consumer Protection & Advocacy Section",
    addressLine1: "2005 North Central Avenue",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85004",
    phone: "(602) 542-5763",
    url: "https://www.azag.gov/consumer",
  },
  AR: {
    name: "Arkansas Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "323 Center Street, Suite 200",
    city: "Little Rock",
    state: "AR",
    zipCode: "72201",
    phone: "(501) 682-2007",
    url: "https://arkansasag.gov/consumer-protection/",
  },
  CA: {
    name: "California Attorney General",
    divisionName: "Public Inquiry Unit",
    addressLine1: "P.O. Box 944255",
    city: "Sacramento",
    state: "CA",
    zipCode: "94244",
    phone: "(800) 952-5225",
    url: "https://oag.ca.gov/consumers",
  },
  CO: {
    name: "Colorado Attorney General",
    divisionName: "Consumer Protection Section",
    addressLine1: "1300 Broadway, 7th Floor",
    city: "Denver",
    state: "CO",
    zipCode: "80203",
    phone: "(720) 508-6000",
    url: "https://coag.gov/office-sections/consumer-protection/",
  },
  CT: {
    name: "Connecticut Attorney General",
    divisionName: "Consumer Protection Department",
    addressLine1: "165 Capitol Avenue",
    city: "Hartford",
    state: "CT",
    zipCode: "06106",
    phone: "(860) 808-5318",
    url: "https://portal.ct.gov/AG/Consumers/Consumer-Complaints",
  },
  DE: {
    name: "Delaware Attorney General",
    divisionName: "Consumer Protection Unit",
    addressLine1: "820 North French Street, 5th Floor",
    city: "Wilmington",
    state: "DE",
    zipCode: "19801",
    phone: "(302) 577-8600",
    url: "https://attorneygeneral.delaware.gov/fraud/cpu/",
  },
  DC: {
    name: "District of Columbia Attorney General",
    divisionName: "Office of Consumer Protection",
    addressLine1: "400 6th Street NW, Suite 10100",
    city: "Washington",
    state: "DC",
    zipCode: "20001",
    phone: "(202) 442-9828",
    url: "https://oag.dc.gov/consumer-protection",
  },
  FL: {
    name: "Florida Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "PL-01, The Capitol",
    city: "Tallahassee",
    state: "FL",
    zipCode: "32399",
    phone: "(850) 414-3990",
    url: "https://www.myfloridalegal.com/consumer-protection",
  },
  GA: {
    name: "Georgia Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "2 Martin Luther King Jr. Drive SE, Suite 356",
    city: "Atlanta",
    state: "GA",
    zipCode: "30334",
    phone: "(404) 651-8600",
    url: "https://consumer.georgia.gov/",
  },
  HI: {
    name: "Hawaii Attorney General",
    divisionName: "Office of Consumer Protection",
    addressLine1: "235 South Beretania Street, Suite 801",
    city: "Honolulu",
    state: "HI",
    zipCode: "96813",
    phone: "(808) 586-2630",
    url: "https://ag.hawaii.gov/office/office-of-consumer-protection/",
  },
  ID: {
    name: "Idaho Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "954 West Jefferson Street, 2nd Floor",
    city: "Boise",
    state: "ID",
    zipCode: "83702",
    phone: "(208) 334-2424",
    url: "https://www.ag.idaho.gov/consumer-protection/",
  },
  IL: {
    name: "Illinois Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "100 West Randolph Street, 12th Floor",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    phone: "(800) 386-5438",
    url: "https://ag.state.il.us/consumers/",
  },
  IN: {
    name: "Indiana Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "302 West Washington Street, 5th Floor",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46204",
    phone: "(317) 232-6201",
    url: "https://www.in.gov/attorneygeneral/consumer-protection-division/",
  },
  IA: {
    name: "Iowa Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "1305 East Walnut Street",
    city: "Des Moines",
    state: "IA",
    zipCode: "50319",
    phone: "(515) 281-5926",
    url: "https://www.iowaattorneygeneral.gov/for-consumers",
  },
  KS: {
    name: "Kansas Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "120 SW 10th Avenue, 2nd Floor",
    city: "Topeka",
    state: "KS",
    zipCode: "66612",
    phone: "(785) 296-3751",
    url: "https://ag.ks.gov/about-the-office/contact-us/file-a-complaint",
  },
  KY: {
    name: "Kentucky Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "1024 Capital Center Drive, Suite 200",
    city: "Frankfort",
    state: "KY",
    zipCode: "40601",
    phone: "(502) 696-5389",
    url: "https://www.ag.ky.gov/Resources/Consumer-Protection",
  },
  LA: {
    name: "Louisiana Attorney General",
    divisionName: "Consumer Protection Section",
    addressLine1: "P.O. Box 94005",
    city: "Baton Rouge",
    state: "LA",
    zipCode: "70804",
    phone: "(225) 326-6465",
    url: "https://www.ag.state.la.us/consumer-protection",
  },
  ME: {
    name: "Maine Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "6 State House Station",
    city: "Augusta",
    state: "ME",
    zipCode: "04333",
    phone: "(207) 626-8849",
    url: "https://www.maine.gov/ag/consumer/index.shtml",
  },
  MD: {
    name: "Maryland Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "200 Saint Paul Place, 16th Floor",
    city: "Baltimore",
    state: "MD",
    zipCode: "21202",
    phone: "(410) 528-8662",
    url: "https://www.marylandattorneygeneral.gov/Pages/CPD/",
  },
  MA: {
    name: "Massachusetts Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "One Ashburton Place, 18th Floor",
    city: "Boston",
    state: "MA",
    zipCode: "02108",
    phone: "(617) 727-8400",
    url: "https://www.mass.gov/orgs/office-of-the-attorney-general",
  },
  MI: {
    name: "Michigan Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 30213",
    city: "Lansing",
    state: "MI",
    zipCode: "48909",
    phone: "(517) 335-7622",
    url: "https://www.michigan.gov/ag/consumer-protection",
  },
  MN: {
    name: "Minnesota Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "445 Minnesota Street, Suite 1400",
    city: "St. Paul",
    state: "MN",
    zipCode: "55101",
    phone: "(651) 296-3353",
    url: "https://www.ag.state.mn.us/Consumer/",
  },
  MS: {
    name: "Mississippi Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 22947",
    city: "Jackson",
    state: "MS",
    zipCode: "39225",
    phone: "(601) 359-4230",
    url: "https://www.ago.state.ms.us/divisions/consumer-protection/",
  },
  MO: {
    name: "Missouri Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 899",
    city: "Jefferson City",
    state: "MO",
    zipCode: "65102",
    phone: "(573) 751-3321",
    url: "https://ago.mo.gov/divisions/consumer-protection/",
  },
  MT: {
    name: "Montana Attorney General",
    divisionName: "Office of Consumer Protection",
    addressLine1: "555 Fuller Avenue",
    city: "Helena",
    state: "MT",
    zipCode: "59601",
    phone: "(406) 444-4500",
    url: "https://dojmt.gov/consumer/",
  },
  NE: {
    name: "Nebraska Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "2115 State Capitol",
    city: "Lincoln",
    state: "NE",
    zipCode: "68509",
    phone: "(402) 471-2682",
    url: "https://ago.nebraska.gov/consumer-protection",
  },
  NV: {
    name: "Nevada Attorney General",
    divisionName: "Bureau of Consumer Protection",
    addressLine1: "555 East Washington Avenue, Suite 3900",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89101",
    phone: "(702) 486-3132",
    url: "https://ag.nv.gov/About/Consumer_Protection/Bureau_of_Consumer_Protection/",
  },
  NH: {
    name: "New Hampshire Attorney General",
    divisionName: "Consumer Protection Bureau",
    addressLine1: "33 Capitol Street",
    city: "Concord",
    state: "NH",
    zipCode: "03301",
    phone: "(603) 271-3641",
    url: "https://www.doj.nh.gov/consumer-protection",
  },
  NJ: {
    name: "New Jersey Attorney General",
    divisionName: "Division of Consumer Affairs",
    addressLine1: "124 Halsey Street, 7th Floor",
    city: "Newark",
    state: "NJ",
    zipCode: "07102",
    phone: "(973) 504-6200",
    url: "https://www.njconsumeraffairs.gov/",
  },
  NM: {
    name: "New Mexico Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "408 Galisteo Street",
    city: "Santa Fe",
    state: "NM",
    zipCode: "87501",
    phone: "(505) 490-4060",
    url: "https://www.nmag.gov/consumer-protection.aspx",
  },
  NY: {
    name: "New York Attorney General",
    divisionName: "Bureau of Consumer Frauds and Protection",
    addressLine1: "28 Liberty Street",
    city: "New York",
    state: "NY",
    zipCode: "10005",
    phone: "(800) 771-7755",
    url: "https://ag.ny.gov/bureau/consumer-frauds-and-protection",
  },
  NC: {
    name: "North Carolina Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "9001 Mail Service Center",
    city: "Raleigh",
    state: "NC",
    zipCode: "27699",
    phone: "(919) 716-6000",
    url: "https://ncdoj.gov/protecting-consumers/",
  },
  ND: {
    name: "North Dakota Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "600 East Boulevard Avenue, Department 125",
    city: "Bismarck",
    state: "ND",
    zipCode: "58505",
    phone: "(701) 328-3404",
    url: "https://attorneygeneral.nd.gov/consumer-resources/",
  },
  OH: {
    name: "Ohio Attorney General",
    divisionName: "Consumer Protection Section",
    addressLine1: "30 East Broad Street, 14th Floor",
    city: "Columbus",
    state: "OH",
    zipCode: "43215",
    phone: "(800) 282-0515",
    url: "https://www.ohioattorneygeneral.gov/Individuals-and-Families/Consumers",
  },
  OK: {
    name: "Oklahoma Attorney General",
    divisionName: "Consumer Protection Unit",
    addressLine1: "313 NE 21st Street",
    city: "Oklahoma City",
    state: "OK",
    zipCode: "73105",
    phone: "(405) 521-2029",
    url: "https://www.oag.ok.gov/consumer-protection",
  },
  OR: {
    name: "Oregon Attorney General",
    divisionName: "Financial Fraud / Consumer Protection Section",
    addressLine1: "1162 Court Street NE",
    city: "Salem",
    state: "OR",
    zipCode: "97301",
    phone: "(877) 877-9392",
    url: "https://www.doj.state.or.us/consumer-protection/",
  },
  PA: {
    name: "Pennsylvania Attorney General",
    divisionName: "Bureau of Consumer Protection",
    addressLine1: "15th Floor, Strawberry Square",
    city: "Harrisburg",
    state: "PA",
    zipCode: "17120",
    phone: "(800) 441-2555",
    url: "https://www.attorneygeneral.gov/protect-yourself/",
  },
  RI: {
    name: "Rhode Island Attorney General",
    divisionName: "Consumer Protection Unit",
    addressLine1: "150 South Main Street",
    city: "Providence",
    state: "RI",
    zipCode: "02903",
    phone: "(401) 274-4400",
    url: "https://riag.ri.gov/consumer-protection",
  },
  SC: {
    name: "South Carolina Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 11549",
    city: "Columbia",
    state: "SC",
    zipCode: "29211",
    phone: "(803) 734-3970",
    url: "https://www.scag.gov/inside-the-office/consumer-protection/",
  },
  SD: {
    name: "South Dakota Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "1302 East Highway 14, Suite 1",
    city: "Pierre",
    state: "SD",
    zipCode: "57501",
    phone: "(605) 773-4400",
    url: "https://consumer.sd.gov/",
  },
  TN: {
    name: "Tennessee Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 20207",
    city: "Nashville",
    state: "TN",
    zipCode: "37202",
    phone: "(615) 741-4737",
    url: "https://www.tn.gov/attorneygeneral/working-for-tennessee/consumer-protection.html",
  },
  TX: {
    name: "Texas Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 12548",
    city: "Austin",
    state: "TX",
    zipCode: "78711",
    phone: "(800) 621-0508",
    url: "https://www.texasattorneygeneral.gov/consumer-protection",
  },
  UT: {
    name: "Utah Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "160 East 300 South, 5th Floor",
    city: "Salt Lake City",
    state: "UT",
    zipCode: "84114",
    phone: "(801) 366-0310",
    url: "https://attorneygeneral.utah.gov/consumer-protection/",
  },
  VT: {
    name: "Vermont Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "109 State Street",
    city: "Montpelier",
    state: "VT",
    zipCode: "05609",
    phone: "(802) 656-3183",
    url: "https://ago.vermont.gov/cap",
  },
  VA: {
    name: "Virginia Attorney General",
    divisionName: "Consumer Protection Section",
    addressLine1: "202 North 9th Street",
    city: "Richmond",
    state: "VA",
    zipCode: "23219",
    phone: "(804) 786-2042",
    url: "https://www.oag.state.va.us/consumer-protection/",
  },
  WA: {
    name: "Washington Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "800 Fifth Avenue, Suite 2000",
    city: "Seattle",
    state: "WA",
    zipCode: "98104",
    phone: "(206) 464-6684",
    url: "https://www.atg.wa.gov/consumer-issues",
  },
  WV: {
    name: "West Virginia Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 1789",
    city: "Charleston",
    state: "WV",
    zipCode: "25326",
    phone: "(304) 558-8986",
    url: "https://ago.wv.gov/consumerprotection/",
  },
  WI: {
    name: "Wisconsin Attorney General",
    divisionName: "Consumer Protection Division",
    addressLine1: "P.O. Box 8935",
    city: "Madison",
    state: "WI",
    zipCode: "53708",
    phone: "(608) 266-1852",
    url: "https://www.doj.state.wi.us/dls/consumer-protection",
  },
  WY: {
    name: "Wyoming Attorney General",
    divisionName: "Consumer Protection Unit",
    addressLine1: "2320 Capitol Avenue",
    city: "Cheyenne",
    state: "WY",
    zipCode: "82002",
    phone: "(307) 777-7874",
    url: "https://ag.wyo.gov/consumer-protection",
  },
} as const satisfies Record<string, StateAGInfo>;

// ============================================================================
// Service of Process Requirements
// ============================================================================

/** Civil service-of-process requirements by state (initial complaints / summons). */
export const SERVICE_REQUIREMENTS = {
  AL: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, process server, or any person over 18. Service by publication allowed when defendant cannot be found.",
  },
  AK: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Process server or any person over 18 who is not a party. Certified mail with return receipt accepted.",
  },
  AZ: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, constable, process server, or any person over 18 who is not a party. Acceptance of service by mail also permitted.",
  },
  AR: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any person over 18. Certified mail with return receipt requested is accepted.",
  },
  CA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 30,
    notes: "Personal service preferred. Substituted service allowed after reasonable diligence (serve someone at home/business + mail copy). Service by publication as last resort.",
  },
  CO: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, process server, or any person over 18. Certified mail with return receipt accepted under C.R.C.P. 4(e).",
  },
  CT: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 15,
    notes: "Service must be made by a state marshal, constable, or indifferent person. Abode service allowed.",
  },
  DE: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any competent person over 18. Certified mail with return receipt accepted for certain actions.",
  },
  DC: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by U.S. Marshal, special process server, or any person over 18 who is not a party.",
  },
  FL: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or certified process server. Substituted service at defendant's usual place of abode with a member of the household over 15.",
  },
  GA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, deputy, or any person over 18 appointed by the court. Acknowledged service also permitted.",
  },
  HI: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, process server, or any person over 18. Certified mail with restricted delivery accepted.",
  },
  ID: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by sheriff or any person over 18 who is not a party. Substituted service at usual place of abode.",
  },
  IL: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any person over 18 who is not a party. Abode service allowed with a family member over 13.",
  },
  IN: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any person at least 18 who is not a party. Certified or registered mail accepted under Trial Rule 4.1.",
  },
  IA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any person over 18. Certified mail or restricted certified mail accepted.",
  },
  KS: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 21,
    notes: "Service by sheriff or any person over 18 who is not a party. First-class mail (certified) with return receipt accepted.",
  },
  KY: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, warning order attorney, or certified mail. Certified mail with return receipt is the default method under CR 4.01.",
  },
  LA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 15,
    notes: "Service by sheriff or court-appointed process server. Domiciliary service allowed when personal service fails.",
  },
  ME: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, deputy, or any person over 18. Certified mail with restricted delivery accepted.",
  },
  MD: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any competent private person over 18. Certified mail accepted under Md. Rule 2-121.",
  },
  MA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, constable, or any person over 18. Certified mail with return receipt accepted for small claims and certain civil actions.",
  },
  MI: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, court officer, or any person over 18. Certified or registered mail with return receipt accepted under MCR 2.105.",
  },
  MN: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any person over 18 who is not a party. Substituted service at last known residence with a person of suitable age.",
  },
  MS: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, process server, or certified mail with return receipt requested under MRCP 4(c)(3).",
  },
  MO: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any person over 18. Certified mail accepted; personal service required for certain actions.",
  },
  MT: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 21,
    notes: "Service by sheriff or any person over 18 who is not a party. Certified mail with return receipt accepted.",
  },
  NE: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any person over 18. Certified mail with return receipt accepted under Neb. Rev. Stat. 25-505.01.",
  },
  NV: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, constable, or any person over 18 who is not a party. Substituted service at usual place of abode.",
  },
  NH: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, deputy, or any person over 18. Certified mail accepted for small claims and some civil actions.",
  },
  NJ: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 35,
    notes: "Service by sheriff, constable, or any person over 18. Certified mail with return receipt accepted. Response deadline is 35 days.",
  },
  NM: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, process server, or any person over 18. Certified mail with return receipt accepted under Rule 1-004.",
  },
  NY: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by any person over 18 who is not a party. Substituted service (nail-and-mail) permitted after due diligence under CPLR 308.",
  },
  NC: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or certified mail with return receipt requested under Rule 4(j). Process server also permitted by court order.",
  },
  ND: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, process server, or any person over 18. Certified mail with return receipt accepted.",
  },
  OH: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 28,
    notes: "Service by certified mail is the default method under Ohio Civ.R. 4.1. Personal service by process server or sheriff also available.",
  },
  OK: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, process server, or certified mail with return receipt. Certified mail is commonly used.",
  },
  OR: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any competent person over 18 who is not a party. First-class mail with declaration of mailing (not certified) for certain filings.",
  },
  PA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or competent adult. Certified mail and acceptance of service also permitted under Pa.R.C.P. 400 et seq.",
  },
  RI: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, constable, or any person over 18. Certified mail with return receipt accepted.",
  },
  SC: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or process server. Certified mail with return receipt accepted under Rule 4(d)(8).",
  },
  SD: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff or any competent person over 18. Certified mail with return receipt accepted.",
  },
  TN: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 30,
    notes: "Service by sheriff, process server, or any person over 18. Certified mail with return receipt accepted under Tenn. R. Civ. P. 4.04.",
  },
  TX: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, constable, or certified process server. Certified mail with return receipt requested accepted under TRCP 106.",
  },
  UT: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, constable, or any person over 18 who is not a party. Service by mail requires court order.",
  },
  VT: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, deputy, or constable. Substituted service at dwelling with a suitable person.",
  },
  VA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 21,
    notes: "Service by sheriff, process server (by court order), or any person over 18. Posting and mailing permitted if personal service fails.",
  },
  WA: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any competent person over 18 who is not a party. Substituted service at usual place of abode with a suitable person.",
  },
  WV: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff or any person over 18. Certified mail or registered mail with return receipt accepted.",
  },
  WI: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: false,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, process server, or any adult who is not a party. Substituted service at usual place of abode.",
  },
  WY: {
    personalService: true,
    substitutedService: true,
    certifiedMailAccepted: true,
    responseDeadlineDays: 20,
    notes: "Service by sheriff, deputy, or any person over 18. Certified mail with return receipt accepted.",
  },
} as const satisfies Record<string, ServiceRequirements>;

// ============================================================================
// FTC Complaint Information
// ============================================================================

/** Federal Trade Commission consumer complaint contact information. */
export const FTC_COMPLAINT_INFO = {
  url: "https://reportfraud.ftc.gov/",
  phone: "1-877-382-4357",
  address: {
    line1: "600 Pennsylvania Avenue NW",
    city: "Washington",
    state: "DC",
    zipCode: "20580",
  },
} as const;
