/**
 * SENTRY API - Analyze Any Letter Text
 *
 * POST /api/sentry/analyze-letter - Analyze any letter for OCR/citation issues
 *
 * This endpoint can analyze existing letters (not generated by Sentry)
 * to provide improvement suggestions.
 */

import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/api-middleware";
import {
  analyzeOCRRisk,
  applyOCRFixes,
  getRiskSummary,
  getImprovementSuggestions,
} from "@/lib/sentry/ocr-detector";
import { validateCitations, getRecommendedCitations } from "@/lib/sentry/legal-validator";
import type { CitationApplicability } from "@/types/sentry";
import { sentryAnalyzeLetterSchema } from "@/lib/api-validation-schemas";
import { createLogger } from "@/lib/logger";
const log = createLogger("sentry-analyze-letter-api");

export const dynamic = "force-dynamic";

// =============================================================================
// POST /api/sentry/analyze-letter - Analyze any letter text
// =============================================================================

export const POST = withAuth(async (req, ctx) => {
  try {
    const body = await req.json();
    const parsed = sentryAnalyzeLetterSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", details: parsed.error.flatten() },
        { status: 400 }
      );
    }
    const { letterContent, targetType, applyFixes } = parsed.data;

    // 1. OCR Analysis
    const ocrAnalysis = analyzeOCRRisk(letterContent);
    const ocrSummary = getRiskSummary(ocrAnalysis);
    const ocrSuggestions = getImprovementSuggestions(ocrAnalysis);

    // 2. Apply fixes if requested
    let fixedContent = null;
    let fixesApplied = null;
    if (applyFixes && ocrAnalysis.autoFixAvailable) {
      const fixResult = applyOCRFixes(letterContent);
      fixedContent = fixResult.fixedContent;
      fixesApplied = fixResult.fixesApplied;
    }

    // 3. Citation Validation
    const citationValidation = validateCitations(letterContent, targetType);
    const recommendedCitations = getRecommendedCitations("accuracy", targetType);

    // 4. Calculate overall quality score
    const qualityScore = calculateQualityScore(ocrAnalysis.score, citationValidation.isValid);

    // 5. Generate improvement recommendations
    const recommendations = generateRecommendations(
      ocrAnalysis,
      citationValidation,
      ocrSuggestions
    );

    return NextResponse.json({
      success: true,
      analysis: {
        // OCR Analysis
        ocr: {
          score: ocrAnalysis.score,
          risk: ocrAnalysis.risk,
          summary: ocrSummary,
          findingCount: ocrAnalysis.findings.length,
          findings: ocrAnalysis.findings.map((f) => ({
            phrase: f.phrase,
            severity: f.severity,
            location: f.location,
            suggestion: f.suggestion,
            explanation: f.explanation,
          })),
          autoFixAvailable: ocrAnalysis.autoFixAvailable,
          improvementSuggestions: ocrSuggestions,
        },

        // Citation Analysis
        citations: {
          isValid: citationValidation.isValid,
          summary: citationValidation.isValid
            ? "All citations appear valid for this recipient type"
            : `Found ${citationValidation.invalidCitations.length} problematic citation(s)`,
          validCitations: citationValidation.validCitations.map((c) => ({
            statute: c.statute,
            name: c.name,
            useFor: c.useFor.slice(0, 3),
          })),
          invalidCitations: citationValidation.invalidCitations.map((c) => ({
            statute: c.statute,
            reason: c.reason,
            suggestion: c.suggestion,
          })),
          warnings: citationValidation.warnings,
          recommended: recommendedCitations.slice(0, 5).map((c) => ({
            statute: c.statute,
            name: c.name,
            description: c.shortDescription,
          })),
        },

        // Overall Assessment
        quality: {
          score: qualityScore,
          grade: getGrade(qualityScore),
          summary: getQualitySummary(qualityScore),
        },

        // Recommendations
        recommendations,

        // Fixed content (if requested)
        ...(applyFixes && fixedContent
          ? {
              fixedContent,
              fixesApplied,
              improvedScore: analyzeOCRRisk(fixedContent).score,
            }
          : {}),
      },
      system: "SENTRY",
    });
  } catch (error) {
    log.error({ err: error }, "Error analyzing letter");
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : "Failed to analyze letter",
        code: "ANALYZE_ERROR",
      },
      { status: 500 }
    );
  }
});

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function calculateQualityScore(ocrScore: number, citationsValid: boolean): number {
  // OCR score is 0-100, citation validity is boolean
  const citationScore = citationsValid ? 100 : 50;

  // Weight: OCR 60%, Citations 40%
  return Math.round(ocrScore * 0.6 + citationScore * 0.4);
}

function getGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

function getQualitySummary(score: number): string {
  if (score >= 90) {
    return "Excellent! This letter has minimal risk of issues.";
  }
  if (score >= 80) {
    return "Good quality letter with minor improvements possible.";
  }
  if (score >= 70) {
    return "Acceptable but could benefit from optimization.";
  }
  if (score >= 60) {
    return "Several issues detected. Review recommendations before sending.";
  }
  return "Significant issues found. Strongly recommend revising this letter.";
}

function generateRecommendations(
  ocrAnalysis: { score: number; risk: string; findings: { severity: string }[] },
  citationValidation: { isValid: boolean; invalidCitations: unknown[] },
  ocrSuggestions: { fix: string; impact: number }[]
): string[] {
  const recommendations: string[] = [];

  // OCR recommendations
  if (ocrAnalysis.risk === "HIGH") {
    recommendations.push(
      "HIGH PRIORITY: This letter has high risk of being flagged as frivolous. Apply OCR fixes immediately."
    );
  } else if (ocrAnalysis.risk === "MEDIUM") {
    recommendations.push(
      "MEDIUM PRIORITY: Several phrases may trigger OCR detection. Consider revising highlighted sections."
    );
  }

  // Add top OCR fix suggestions
  const topSuggestions = ocrSuggestions.slice(0, 3);
  for (const suggestion of topSuggestions) {
    recommendations.push(suggestion.fix);
  }

  // Citation recommendations
  if (!citationValidation.isValid) {
    recommendations.push(
      `FIX REQUIRED: ${citationValidation.invalidCitations.length} legal citation(s) are incorrect or misapplied.`
    );
  }

  // General tips
  if (ocrAnalysis.findings.filter((f) => f.severity === "HIGH").length > 0) {
    recommendations.push(
      "Remove demanding or threatening language - bureaus flag this as template content."
    );
  }

  if (recommendations.length === 0) {
    recommendations.push(
      "This letter looks good! Consider adding Metro 2 field targeting for better results."
    );
  }

  return recommendations;
}
