// ============================================================================
// DISPUTE2GO - Hooks Index
// Export all hooks from a single entry point
// ============================================================================

// Generic API hooks
export {
  useApiQuery,
  useMutation,
  useInfiniteQuery,
  useDebounce,
  usePrevious,
  type UseApiQueryResult,
  type UseApiQueryOptions,
  type UseMutationResult,
  type UseMutationOptions,
  type UseInfiniteQueryResult,
  type UseInfiniteQueryOptions,
} from './use-api';

// Client hooks
export {
  useClients,
  useClient,
  useClientAccounts,
  useClientNegativeAccounts,
  useClientReports,
  useClientDisputes,
  useClientTimeline,
  useArchivedClients,
  useCreateClient,
  useUpdateClient,
  useDeleteClient,
  useUpdateClientStage,
  useUpdateClientPriority,
  useArchiveClient,
  useRestoreClient,
  useUploadReport,
  useClientFullName,
  useClientInitials,
  useAverageCreditScore,
  useAccountsByCRA,
  useAccountsByStatus,
  useNegativeAccounts,
  useClientStats,
  useClientSearch,
  type Client,
  type CreditScores,
  type ClientAccount,
  type ClientReport,
  type TimelineEvent,
  type ClientListParams,
  type ClientListResponse,
  type CreateClientData,
  type UpdateClientData,
  type AccountsParams,
} from './use-clients';

// Dispute hooks
export {
  useDisputes,
  useDispute,
  useDisputeLetter,
  usePendingResponses,
  useDisputesNeedingAction,
  useClientDisputesList,
  useDisputesByStatus,
  useDisputesByCRA,
  useLetterPreview,
  useCreateDispute,
  useUpdateDispute,
  useDeleteDispute,
  useApproveDispute,
  useMarkDisputeSent,
  useLogResponse,
  useUpdateLetter,
  useRegenerateLetter,
  useDownloadDocx,
  useDownloadPdf,
  useBulkUpdateDisputes,
  useDaysUntilDeadline,
  useIsOverdue,
  useDisputesByStatusGroup,
  useDisputesByCRAGroup,
  useDisputesByFlowGroup,
  useDisputeStats,
  useOverdueResponses,
  useSortedDisputesByUrgency,
  type Dispute,
  type DisputeDocument,
  type DisputeLetter,
  type LetterSection,
  type DisputeListParams,
  type DisputeListResponse,
  type PendingResponse,
  type DisputeNeedingAction,
  type CreateDisputeData,
  type UpdateDisputeData,
  type LogResponseData,
  type MarkSentData,
  type RegenerateLetterOptions,
} from './use-disputes';

// AMELIA AI hooks
export {
  useCreditDNA,
  useAmeliaInsights,
  useRecommendedFlow,
  useToneRecommendation,
  useEoscarCheck,
  useRegenerateSection,
  useGenerateDispute,
  useGenerateCFPB,
  useRefreshCreditDNA,
  useInsightsByType,
  useHighPriorityInsights,
  useSortedInsights,
  useCreditDNAHealthColor,
  useTopRecommendations,
  useRiskFactorsBySeverity,
  useEoscarResistanceLevel,
  useFlowRecommendationsByType,
  useAverageConfidence,
  type AmeliaInsight,
  type AccountInsightRequest,
  type AccountForInsight,
  type ClientHistory,
  type InsightOptions,
  type FlowRecommendation,
  type ToneRecommendation,
  type EoscarCheckResult,
  type EoscarVulnerability,
  type CreditDNA,
  type CreditDNAAnalysis,
  type CreditDNARecommendation,
  type CreditDNARiskFactor,
  type CreditDNAOpportunity,
  type RegenerateSectionRequest,
  type GeneratedSection,
  type DisputeGenerationRequest,
  type GeneratedDispute,
  type CFPBGenerationRequest,
  type GeneratedCFPB,
} from './use-amelia';

// Analytics hooks
export {
  useDashboardStats,
  useSuccessRateByCRA,
  useSuccessRateByFlow,
  useMonthlyTrends,
  useClientFunnel,
  useViolationStats,
  useAllAnalytics,
  useOverallSuccessRate,
  useBestPerformingCRA,
  useBestPerformingFlow,
  useTrendDirection,
  useFormattedTrendsForChart,
  useFunnelConversionRates,
  useTopViolations,
  useCRAComparisonData,
  useAverageResolutionTime,
  useAverageRounds,
  useKPIs,
  useMonthOverMonthGrowth,
  type DashboardStats,
  type SuccessRateByCRA,
  type SuccessRateByFlow,
  type MonthlyTrend,
  type ClientFunnelStats,
  type ViolationStats,
  type AnalyticsData,
} from './use-analytics';
