/**
 * Sentry Execute API
 *
 * POST /api/sentry/execute
 * Executes a Sentry dispute plan by creating disputes via the existing
 * unified dispute creation pipeline with type: "sentry".
 */

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { createUnifiedDispute } from "@/lib/dispute-creation";
import { fetchAndValidateClient, fetchAndValidateAccounts } from "@/lib/dispute-creation/validation";
import type { CreateDisputeContext } from "@/lib/dispute-creation/create-dispute";
import type { SentryDisputePlan } from "@/lib/sentry/types";
import { createLogger } from "@/lib/logger";

const log = createLogger("sentry-execute-api");

export const dynamic = "force-dynamic";

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { clientId, plan, reviewNotes } = body as {
      clientId: string;
      plan: SentryDisputePlan;
      reviewNotes?: string;
    };

    if (!clientId || !plan) {
      return NextResponse.json({ error: "clientId and plan are required" }, { status: 400 });
    }

    // Verify client belongs to org
    const client = await prisma.client.findFirst({
      where: { id: clientId, organizationId: session.user.organizationId },
    });

    if (!client) {
      return NextResponse.json({ error: "Client not found" }, { status: 404 });
    }

    const createdDisputes = [];

    // Fetch full client data for dispute context
    const { client: fullClient, error: clientFetchError } = await fetchAndValidateClient(
      clientId,
      session.user.organizationId
    );

    if (!fullClient) {
      return NextResponse.json({ error: clientFetchError || "Client not found" }, { status: 404 });
    }

    // Create disputes for each bureau group
    for (const group of plan.bureauGroups) {
      const accountIds = group.accounts.map((a) => a.accountId);

      try {
        // Fetch accounts for this bureau group
        const { accounts } = await fetchAndValidateAccounts(
          accountIds,
          session.user.organizationId,
          clientId,
          group.cra as "TRANSUNION" | "EXPERIAN" | "EQUIFAX"
        );

        const context: CreateDisputeContext = {
          client: fullClient,
          accounts,
          organizationId: session.user.organizationId,
          userId: session.user.id,
          userEmail: session.user.email || "",
        };

        const result = await createUnifiedDispute({
          type: "sentry",
          clientId,
          accountIds,
          cra: group.cra as "TRANSUNION" | "EXPERIAN" | "EQUIFAX",
          flow: group.flow,
          sentryContext: {
            eoscarCodes: group.accounts.flatMap((a) =>
              a.eoscarRecommendations.slice(0, 2).map((r) => r.code)
            ),
            metro2Targets: group.accounts.flatMap((a) =>
              a.metro2Targets.map((t) => t.field.code)
            ),
          },
        }, context);

        if (result.success) {
          // Mark disputes as sentry-generated
          for (const dispute of result.disputes) {
            await prisma.dispute.update({
              where: { id: dispute.disputeId },
              data: { sentryGenerated: true },
            });

            // Create SentryAnalysis record
            const accountAnalyses = group.accounts;
            const topRecs = accountAnalyses.flatMap((a) => a.eoscarRecommendations.slice(0, 3));
            const avgSuccess =
              accountAnalyses.reduce((s, a) => s + a.successProbability.probability, 0) /
              accountAnalyses.length;

            await prisma.sentryAnalysis.create({
              data: {
                disputeId: dispute.disputeId,
                eoscarCodes: JSON.stringify(topRecs.map((r) => r.code)),
                eoscarRecommendations: JSON.stringify(topRecs),
                citationsValidated: true,
                ocrRiskScore: 80, // Will be updated after letter generation
                metro2Fields: JSON.stringify(
                  accountAnalyses.flatMap((a) => a.metro2Targets)
                ),
                successProbability: avgSuccess,
                successBreakdown: JSON.stringify(
                  accountAnalyses[0]?.successProbability.breakdown || []
                ),
                sentryModeActive: true,
                autoGenerated: true,
                reviewedByUserId: reviewNotes ? session.user.id : null,
                reviewedAt: reviewNotes ? new Date() : null,
              },
            });
          }

          createdDisputes.push(...result.disputes);
        }
      } catch (err) {
        log.error({ err, cra: group.cra }, "Failed to create dispute for bureau group");
      }
    }

    // Log activity
    await prisma.sentryActivityLog.create({
      data: {
        organizationId: session.user.organizationId,
        clientId,
        activityType: "DISPUTES_CREATED",
        summary: `Sentry created ${createdDisputes.length} disputes from plan with ${plan.totalAccounts} accounts`,
        details: JSON.stringify({
          disputeCount: createdDisputes.length,
          reviewNotes,
          disputeIds: createdDisputes.map((d) => d.disputeId),
        }),
        triggeredBy: session.user.id,
      },
    });

    return NextResponse.json({
      success: true,
      disputesCreated: createdDisputes.length,
      disputes: createdDisputes,
    });
  } catch (error) {
    log.error({ err: error }, "Sentry execute failed");
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Execution failed" },
      { status: 500 }
    );
  }
}
