import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
import { SkipLink } from "@/components/ui/skip-link";
import { CookieConsent } from "@/components/cookie-consent";

const inter = Inter({ subsets: ["latin"], variable: "--font-geist-sans" });

export const metadata: Metadata = {
  metadataBase: new URL("https://dispute2go.com"),
  title: {
    default: "Dispute2Go | AI-Powered Credit Repair Software",
    template: "%s | Dispute2Go",
  },
  description: "Fix credit faster with AI-generated dispute letters. Automated workflows, bureau tracking, and compliance built-in. Start your free trial today.",
  keywords: ["credit repair", "dispute letters", "FCRA", "credit bureau", "CRA disputes", "credit repair software", "AI credit repair"],
  icons: {
    icon: "/icon.png",
    apple: "/apple-icon.png",
  },
  // Open Graph - for iMessage, Facebook, LinkedIn, etc.
  // Images auto-generated by opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://dispute2go.com",
    siteName: "Dispute2Go",
    title: "Dispute2Go | AI-Powered Credit Repair Software",
    description: "Fix credit faster with AI-generated dispute letters. Automated workflows, bureau tracking, and compliance built-in.",
  },
  // Twitter Card - Images auto-generated by twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: "Dispute2Go | AI-Powered Credit Repair Software",
    description: "Fix credit faster with AI-generated dispute letters. Automated workflows, bureau tracking, and compliance built-in.",
    creator: "@dispute2go",
  },
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        <SkipLink />
        <Providers>
          {children}
          <Toaster />
        </Providers>
        <CookieConsent />
      </body>
    </html>
  );
}
